### ISSUE TITLE
make: *** [bin/pandoc] Error 1 make: *** [all] Error 2`

### ISSUE THREAD

**Issue by ghost** [claudiajs/pandoc-aws-lambda-binary#7]
I'm getting this error:

`cabal: The following packages are likely to be broken by the reinstalls:
parsec-3.1.13.0
Cabal-2.2.0.1
Use --force-reinstalls if you want to install anyway.

make: *** [bin/pandoc] Error 1
make: *** [all] Error 2`

Do you know how to fix this?

**Comment by ghost** [comment]
I have solve rebuilding and using --force-reinstalls

**but now I get this error on AWS Lambda:**
`[ERROR] RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: HOME: getXdgDirectory:getHomeDirectory:getEnv: does not exist (no environment variable)\n'
Traceback (most recent call last):
  File "/var/task/index.py", line 26, in handler
    output_path = handle_pandoc(document_path, key_output_file, to_convert)
  File "/var/task/index.py", line 66, in handle_pandoc
    pypandoc.convert_file(input_path, to_convert, outputfile=output_path)
  File "/opt/python/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/opt/python/lib/python3.8/site-packages/pypandoc/__init__.py", line 320, in _convert_input
    raise RuntimeError(`

if I add 
`logging.info(os.system("pandoc --version"))`
I get
`pandoc: HOME: getXdgDirectory:getHomeDirectory:getEnv: does not exist (no environment variable)
`
